FROM php:8.1-apache

# Instalar dependencias necesarias antes de compilar extensiones PHP
RUN apt-get update && apt-get install -y \
    libzip-dev \
    libpng-dev \
    libjpeg-dev \
    libonig-dev \
    libxml2-dev \
    unzip \
    curl \
    vim \
    && docker-php-ext-install mysqli pdo pdo_mysql \
    && docker-php-ext-enable mysqli \
    && rm -rf /var/lib/apt/lists/*

# Establecer permisos adecuados para los archivos web
RUN chown -R www-data:www-data /var/www/html

EXPOSE 80
